version: "3"
services:
  kafka:
    image: wurstmeister/kafka:latest
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_NAMES: INSIDE,OUTSIDE
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  stock-data-service:
    image: nguyenduchuy782/stock-data-service:latest
    ports:
      - "3001:3001"
    depends_on:
      - kafka

  database-service:
    image: nguyenduchuy782/database-service:latest
    ports:
      - "3002:3002"
    environment:
      - MONGO_URI=mongodb+srv://fisave-admin:kRdp07zIoB4DbQqP@fisave-cluster.4wvppvv.mongodb.net/Server
    depends_on:
      - mongodb

  notification-service:
    image: nguyenduchuy782/notification-service:latest
    ports:
      - "3003:3003"

  kafka-producer:
    image: nguyenduchuy782/kafka-producer:latest
    depends_on:
      - kafka

  kafka-consumer:
    image: nguyenduchuy782/kafka-consumer:latest
    depends_on:
      - kafka
      - mongodb

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - stock-data-service
      - database-service
      - notification-service
